# Site settings
title: 中国容积党中央委员会 # 你的博客名字，可以定义修订
header-img: "img/red.jpg"
tagline: "cn"  
description: "这是我的博客"  # 一句话描述你的博客
baseurl: ""
url: "https://ovule-seed.github.io/"  # 此处填写你的博客地址 

# About/contact
owner: 
  name: "123" # 填写作者信息：名字
  email: 2447920685@qq.com # 填写作者信息：邮箱
  bio: "中容中央general secretary" # 填写作者信息：博客描述

# Data
gavatar: img/favico.png # 浏览器地址栏小图标，可自定义更改
favicon: img/favico.png # 浏览器地址栏小图标，可自定义更改

douban_username: 没有豆瓣账号但是空着不好看 # 你的豆瓣id
twitter_username: 没有推特账号但是空着不好看
github_username: ovule-seed
facebook_username: Abandon Abdonment
weibo_username: 没有厕所账号但是空着不好看
zhihu_username: 没有知乎账好但是空着不好看

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "ovuleseed" # 你的名字
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus # 使用 disqus 评论模块，读者翻墙才能看见
  duoshuo :
    short_name : ovuleseed # 填写你的 disqus id
  disqus :
      short_name : ovuleseed # 填写你的 disqus id

# Analytics and webmaster tools stuff goes here
google_analytics:  # 填写你  google_analytics id
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation


post_asset_folder: true

# Support for LiveRe comments system.
# You can get your uid from https://www.livere.com/my_Livere
livere_uid: MTAyMC81ODAwMC8zNDQ2Mw==
